# Generated by Django 3.0.2 on 2020-01-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200129_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
